project:
  type: website
  output-dir: docs

website:
  title: "HI RevealJS Slides Template"

format:
  revealjs:
    theme: simple
    title-slide: false
    slide-number: true
    show-slide-number: all
    controls: true
    progress: true
    incremental: false
    transition: fade
    background-transition: fade
    css: styles.css
    width: 1600
    height: 900
    center: false
    include-in-header:
      - hi-branding.html
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />

execute:
  warning: false
  message: false
